// Division A (Rating 85)
export const PLAYERS_A = [
  // Cavalry
  { name: "Inspire", category: "CAVALRY", clan: "RPGS", rating: 85 },
  { name: "Popo", category: "CAVALRY", clan: "IE", rating: 85 },
  { name: "Siberia", category: "CAVALRY", clan: "VW", rating: 85 },
  { name: "Mimieux", category: "CAVALRY", clan: "IE", rating: 85 },
  { name: "Reg", category: "CAVALRY", clan: "IE2", rating: 85 },
  { name: "troechka", category: "CAVALRY", clan: "RPGS", rating: 85 },
  { name: "Kajzer", category: "CAVALRY", clan: "KoPL", rating: 85 },
  { name: "chupapi", category: "CAVALRY", clan: "Div", rating: 85 },
  { name: "Firunien", category: "CAVALRY", clan: "Div", rating: 85 },
  { name: "Authari", category: "CAVALRY", clan: "VW", rating: 85 },
  { name: "Qaxey", category: "CAVALRY", clan: "IE2", rating: 85 },
  { name: "Aela", category: "CAVALRY", clan: "KoPL", rating: 85 },
  { name: "Merminal", category: "CAVALRY", clan: "IE2", rating: 85 },
  { name: "albie", category: "CAVALRY", clan: "IE", rating: 85 },

  // Archer
  { name: "Koso", category: "ARCHER", clan: "IE", rating: 85 },
  { name: "Aesten", category: "ARCHER", clan: "VW", rating: 85 },
  { name: "Longinus", category: "ARCHER", clan: "IE", rating: 85 },
  { name: "royal", category: "ARCHER", clan: "IE2", rating: 85 },
  { name: "saviour", category: "ARCHER", clan: "RPGS", rating: 85 },
  { name: "Shav", category: "ARCHER", clan: "Div", rating: 85 },
  { name: "Ahoen", category: "ARCHER", clan: "KoPL", rating: 85 },

  // Infantry
  { name: "SMASH", category: "INFANTRY", clan: "IE", rating: 85 },
  { name: "Nutella", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Pablo", category: "INFANTRY", clan: "RPGS", rating: 85 },
  { name: "Burst", category: "INFANTRY", clan: "IE2", rating: 85 },
  { name: "cleqfy", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Joker", category: "INFANTRY", clan: "IE2", rating: 85 },
  { name: "Arni", category: "INFANTRY", clan: "IE", rating: 85 },
  { name: "DarkLight", category: "INFANTRY", clan: "IE", rating: 85 },
  { name: "Carlos", category: "INFANTRY", clan: "IE2", rating: 85 },
  { name: "Ari", category: "INFANTRY", clan: "KoPL", rating: 85 },
  { name: "Zom54p", category: "INFANTRY", clan: "IE", rating: 85 },
  { name: "Nomis", category: "INFANTRY", clan: "VW", rating: 85 },
  { name: "Tazatko", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Nightwing", category: "INFANTRY", clan: "IE2", rating: 85 },
  { name: "Reincarnation", category: "INFANTRY", clan: "RPGS", rating: 85 },
  { name: "MysteriousHero", category: "INFANTRY", clan: "RPGS", rating: 85 },
  { name: "Shkiper", category: "INFANTRY", clan: "RPGS", rating: 85 },
  { name: "Thoros", category: "INFANTRY", clan: "VW", rating: 85 },
  { name: "dertli kemanci", category: "INFANTRY", clan: "VW", rating: 85 },
  { name: "Big G", category: "INFANTRY", clan: "KoPL", rating: 85 },
  { name: "Silver", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Lam", category: "INFANTRY", clan: "VW", rating: 85 },
  { name: "pyncook", category: "INFANTRY", clan: "KoPL", rating: 85 },
  { name: "Fylyp", category: "INFANTRY", clan: "KoPL", rating: 85 },
  { name: "Mert", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Enter", category: "INFANTRY", clan: "Div", rating: 85 },
  { name: "Shrek", category: "INFANTRY", clan: "KoPL", rating: 85 },
]

// Division B (Rating 80)
export const PLAYERS_B = [
  { name: "SirAlecks", category: "CAVALRY", clan: "HCI", rating: 80 },
  { name: "Dark Vader", category: "CAVALRY", clan: "DB", rating: 80 },
  { name: "Infinant", category: "CAVALRY", clan: "HCI", rating: 80 },
  { name: "Virdena", category: "ARCHER", clan: "RPGS2", rating: 80 },
  { name: "Primus", category: "CAVALRY", clan: "DB", rating: 80 },
  { name: "Aary", category: "CAVALRY", clan: "Blue", rating: 80 },
  { name: "Sturgeon", category: "CAVALRY", clan: "HCI", rating: 80 },
  { name: "Bunny", category: "ARCHER", clan: "HCI", rating: 80 },
  { name: "Sneaky", category: "CAVALRY", clan: "RPGS2", rating: 80 },
  { name: "Smyky", category: "CAVALRY", clan: "TCV", rating: 80 },
  { name: "Arthur", category: "ARCHER", clan: "DB", rating: 80 },
  { name: "Lumari", category: "CAVALRY", clan: "TCV", rating: 80 },
  { name: "CARNIFEX", category: "CAVALRY", clan: "RPGS2", rating: 80 },
  { name: "Chuckster", category: "INFANTRY", clan: "Blue", rating: 80 },
  { name: "Sunny", category: "INFANTRY", clan: "TCV", rating: 80 },
  { name: "Aiku", category: "INFANTRY", clan: "RPGS2", rating: 80 },
  { name: "Retamar", category: "ARCHER", clan: "Blue", rating: 80 },
  { name: "BD", category: "INFANTRY", clan: "HCI", rating: 80 },
  { name: "EnderKlas", category: "INFANTRY", clan: "RPGS2", rating: 80 },
  { name: "Thyrell", category: "INFANTRY", clan: "TCV", rating: 80 },
  { name: "DragonKing", category: "CAVALRY", clan: "Blue", rating: 80 },
  { name: "Kenny", category: "INFANTRY", clan: "HCI", rating: 80 },
  { name: "Gamblegis", category: "INFANTRY", clan: "Blue", rating: 80 },
  { name: "Runcop", category: "INFANTRY", clan: "TCV", rating: 80 },
  { name: "Alsandair", category: "INFANTRY", clan: "HCI", rating: 80 },
  { name: "Prez", category: "INFANTRY", clan: "RPGS2", rating: 80 },
  { name: "GerarDus", category: "INFANTRY", clan: "DB", rating: 80 },
  { name: "Bombbooo", category: "INFANTRY", clan: "DB", rating: 80 },
  { name: "Rigo", category: "INFANTRY", clan: "Blue", rating: 80 },
  { name: "Incognita", category: "INFANTRY", clan: "DB", rating: 80 },
  { name: "Bladimus", category: "INFANTRY", clan: "HCI", rating: 80 },
  { name: "Delta", category: "INFANTRY", clan: "DB", rating: 80 },
  { name: "Yosh", category: "INFANTRY", clan: "DB", rating: 80 },
  { name: "Cadavre", category: "INFANTRY", clan: "Blue", rating: 80 },
  { name: "Valenor", category: "INFANTRY", clan: "Blue", rating: 80 },
  { name: "CunnieBBG", category: "INFANTRY", clan: "RPGS2", rating: 80 },
  { name: "Azrael", category: "INFANTRY", clan: "TCV", rating: 80 },
  { name: "Samatko", category: "INFANTRY", clan: "HCI", rating: 80 },
  { name: "Jake", category: "INFANTRY", clan: "TCV", rating: 80 },
]

// Division C (Rating 75)
export const PLAYERS_C = [
  { name: "marauder", category: "CAVALRY", clan: "DW", rating: 75 },
  { name: "Camm15elbe", category: "CAVALRY", clan: "YT", rating: 75 },
  { name: "Demivar", category: "CAVALRY", clan: "ZE", rating: 75 },
  { name: "Altar of The Manes", category: "CAVALRY", clan: "DW", rating: 75 },
  { name: "Ceh", category: "CAVALRY", clan: "DW", rating: 75 },
  { name: "Verox", category: "ARCHER", clan: "ZE", rating: 75 },
  { name: "Karmaz", category: "CAVALRY", clan: "SVRN", rating: 75 },
  { name: "Artemisia", category: "ARCHER", clan: "SVRN", rating: 75 },
  { name: "dhmi", category: "CAVALRY", clan: "SVRN", rating: 75 },
  { name: "Ramsus", category: "ARCHER", clan: "YT", rating: 75 },
  { name: "Neena", category: "CAVALRY", clan: "HINQ", rating: 75 },
  { name: "Angel", category: "CAVALRY", clan: "HINQ", rating: 75 },
  { name: "Biathman", category: "ARCHER", clan: "HINQ", rating: 75 },
  { name: "Achilles", category: "INFANTRY", clan: "YT", rating: 75 },
  { name: "Ghost", category: "CAVALRY", clan: "RF", rating: 75 },
  { name: "Hlafis", category: "CAVALRY", clan: "ZE", rating: 75 },
  { name: "Quadri", category: "ARCHER", clan: "HINQ", rating: 75 },
  { name: "Hancock", category: "ARCHER", clan: "DW", rating: 75 },
  { name: "Jungle VIP", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "Gudvin", category: "INFANTRY", clan: "HINQ", rating: 75 },
  { name: "Jujana", category: "INFANTRY", clan: "RF", rating: 75 },
  { name: "HANWER", category: "INFANTRY", clan: "HINQ", rating: 75 },
  { name: "Gaz", category: "INFANTRY", clan: "RF", rating: 75 },
  { name: "hwenson", category: "CAVALRY", clan: "ZE", rating: 75 },
  { name: "dgsegse", category: "ARCHER", clan: "RF", rating: 75 },
  { name: "Cody", category: "CAVALRY", clan: "YT", rating: 75 },
  { name: "Ike", category: "ARCHER", clan: "YT", rating: 75 },
  { name: "NinjaBread Guy", category: "INFANTRY", clan: "SVRN", rating: 75 },
  { name: "Aurora", category: "INFANTRY", clan: "SVRN", rating: 75 },
  { name: "RayZen", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "Herishey", category: "CAVALRY", clan: "RF", rating: 75 },
  { name: "Kloney", category: "INFANTRY", clan: "SVRN", rating: 75 },
  { name: "Late", category: "INFANTRY", clan: "RF", rating: 75 },
  { name: "hallow", category: "INFANTRY", clan: "SVRN", rating: 75 },
  { name: "Microsoft Paperclip", category: "CAVALRY", clan: "YT", rating: 75 },
  { name: "Crusader5", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "vemon", category: "INFANTRY", clan: "YT", rating: 75 },
  { name: "Dutch", category: "INFANTRY", clan: "ZE", rating: 75 },
  { name: "Kargath", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "Scovis", category: "INFANTRY", clan: "ZE", rating: 75 },
  { name: "Fietta", category: "INFANTRY", clan: "YT", rating: 75 },
  { name: "Lasand", category: "INFANTRY", clan: "RF", rating: 75 },
  { name: "SHype", category: "INFANTRY", clan: "YT", rating: 75 },
  { name: "XKTD", category: "INFANTRY", clan: "ZE", rating: 75 },
  { name: "IsrafeI", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "Kilian", category: "INFANTRY", clan: "ZE", rating: 75 },
  { name: "Nex", category: "INFANTRY", clan: "DW", rating: 75 },
  { name: "janne", category: "INFANTRY", clan: "RF", rating: 75 },
  { name: "Doomers", category: "INFANTRY", clan: "HINQ", rating: 75 },
  { name: "Sarrah", category: "INFANTRY", clan: "ZE", rating: 75 },
  { name: "Alpharius", category: "INFANTRY", clan: "DW", rating: 75 },
]

// Division D (Rating 70)
export const PLAYERS_D = [
  { name: "AlpEr Tunga", category: "CAVALRY", clan: "KSM", rating: 70 },
  { name: "MluBa", category: "CAVALRY", clan: "IZpp", rating: 70 },
  { name: "Mono", category: "CAVALRY", clan: "VW", rating: 70 },
  { name: "thetis", category: "CAVALRY", clan: "KSM", rating: 70 },
  { name: "Piña", category: "ARCHER", clan: "Eque", rating: 70 },
  { name: "krex", category: "CAVALRY", clan: "Eque", rating: 70 },
  { name: "Sir Killer", category: "CAVALRY", clan: "CI", rating: 70 },
  { name: "Traesercon", category: "CAVALRY", clan: "CI", rating: 70 },
  { name: "Fergus", category: "CAVALRY", clan: "Wonw", rating: 70 },
  { name: "Troulax", category: "CAVALRY", clan: "VW", rating: 70 },
  { name: "Ice", category: "CAVALRY", clan: "Eque", rating: 70 },
  { name: "MlyTax", category: "CAVALRY", clan: "IZpp", rating: 70 },
  { name: "hoonii", category: "CAVALRY", clan: "VW", rating: 70 },
  { name: "Vicente", category: "CAVALRY", clan: "Wonw", rating: 70 },
  { name: "iZokerX", category: "CAVALRY", clan: "CI", rating: 70 },
  { name: "Rolf", category: "ARCHER", clan: "KSM", rating: 70 },
  { name: "bella", category: "CAVALRY", clan: "Wonw", rating: 70 },
  { name: "Feevka", category: "CAVALRY", clan: "KSM", rating: 70 },
  { name: "crazy baba", category: "ARCHER", clan: "VW", rating: 70 },
  { name: "Meridio", category: "ARCHER", clan: "CI", rating: 70 },
  { name: "Torantes", category: "CAVALRY", clan: "Wonw", rating: 70 },
  { name: "timo", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "Anthony", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "Janeka", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "iamBananaJoe", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "BUSHI", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "Beano", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "AgmunD", category: "CAVALRY", clan: "VW", rating: 70 },
  { name: "pope", category: "INFANTRY", clan: "IZpp", rating: 70 },
  { name: "heiho", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "Robert", category: "ARCHER", clan: "Wonw", rating: 70 },
  { name: "Svoboda", category: "CAVALRY", clan: "Eque", rating: 70 },
  { name: "Drago", category: "INFANTRY", clan: "IZpp", rating: 70 },
  { name: "g21hawk", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "Wodlapato", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "Sutrupa", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "Canta", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "Porkins", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "Milosz", category: "INFANTRY", clan: "IZpp", rating: 70 },
  { name: "Noble", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "Termito", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "Dreamo", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "Thranduil", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "Thornfinn", category: "INFANTRY", clan: "IZpp", rating: 70 },
  { name: "Fevta", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "Ragnar", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "ViciousFate", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "Nheolo of Rhodes", category: "INFANTRY", clan: "CI", rating: 70 },
  { name: "Bardin Goreskson", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "Soomer", category: "INFANTRY", clan: "IZpp", rating: 70 },
  { name: "Divola", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "JAff", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "HitAndGun", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "Joglemogelgels", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "Raven", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "Rotseakh", category: "INFANTRY", clan: "KSM", rating: 70 },
  { name: "Arnn", category: "INFANTRY", clan: "VW", rating: 70 },
  { name: "Asuna", category: "INFANTRY", clan: "Eque", rating: 70 },
  { name: "EVIL DOG", category: "INFANTRY", clan: "Wonw", rating: 70 },
  { name: "senni", category: "INFANTRY", clan: "Eque", rating: 70 },
]

// Division E (Rating 65)
export const PLAYERS_E = [
  { name: "Brox", category: "CAVALRY", clan: "Bloody Disaster", rating: 65 },
  { name: "AsianBunny X", category: "CAVALRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Castron", category: "ARCHER", clan: "Lions of God", rating: 65 },
  { name: "Sir Ezequiel", category: "CAVALRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "JustGarez", category: "CAVALRY", clan: "Rising Reign", rating: 65 },
  { name: "Terrorist Killer", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "Fazv", category: "CAVALRY", clan: "Inek Obasi", rating: 65 },
  { name: "Malcolm", category: "CAVALRY", clan: "Hells Angels", rating: 65 },
  { name: "Majestica", category: "CAVALRY", clan: "Lions of God", rating: 65 },
  { name: "Bobstergon", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Skittles", category: "CAVALRY", clan: "Bloody Disaster", rating: 65 },
  { name: "GameHonor", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "Royalus", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "Blue", category: "ARCHER", clan: "Bloody Disaster", rating: 65 },
  { name: "Rauber", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Aris", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "ioz", category: "CAVALRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Tomppa", category: "ARCHER", clan: "Eque Wheelchair", rating: 65 },
  { name: "Sauron", category: "CAVALRY", clan: "Rising Reign", rating: 65 },
  { name: "dubceac", category: "INFANTRY", clan: "Inek Obasi", rating: 65 },
  { name: "Vio", category: "CAVALRY", clan: "Rising Reign", rating: 65 },
  { name: "Mose", category: "INFANTRY", clan: "Lions of God", rating: 65 },
  { name: "Va", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Sait", category: "ARCHER", clan: "Hells Angels", rating: 65 },
  { name: "Unwind", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "Fortes", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
  { name: "Cerci", category: "CAVALRY", clan: "Inek Obasi", rating: 65 },
  { name: "Margar", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Buck50", category: "CAVALRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Nightingale", category: "CAVALRY", clan: "Lions of God", rating: 65 },
  { name: "Subridens", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
  { name: "TheGioMan", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Baycu", category: "INFANTRY", clan: "Inek Obasi", rating: 65 },
  { name: "Ather", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Grillon", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
  { name: "Hundi", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Patavastiz", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
  { name: "Xavi Leon", category: "CAVALRY", clan: "Lions of God", rating: 65 },
  { name: "Joa", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "Rando", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Bem", category: "ARCHER", clan: "Bloody Disaster", rating: 65 },
  { name: "Creed", category: "INFANTRY", clan: "Hells Angels", rating: 65 },
  { name: "hoony", category: "INFANTRY", clan: "Inek Obasi", rating: 65 },
  { name: "Crusader", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Mitchell", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Myrrine", category: "INFANTRY", clan: "Eque Wheelchair", rating: 65 },
  { name: "Zap", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Sypruss", category: "INFANTRY", clan: "Inek Obasi", rating: 65 },
  { name: "Cagey", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "njord", category: "INFANTRY", clan: "Inek Obasi", rating: 65 },
  { name: "Death", category: "INFANTRY", clan: "Bloody Disaster", rating: 65 },
  { name: "Omar", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
  { name: "Kaisareia", category: "INFANTRY", clan: "Rising Reign", rating: 65 },
]

// Division F (Rating 60)
export const PLAYERS_F = [
  { name: "Spud", category: "CAVALRY", clan: "Asbanir", rating: 60 },
  { name: "Sam", category: "CAVALRY", clan: "Asbanir", rating: 60 },
  { name: "Quesek", category: "CAVALRY", clan: "IZpp Ingles", rating: 60 },
  { name: "flavberg", category: "CAVALRY", clan: "DRAC", rating: 60 },
  { name: "Orcus Wan Kenobi", category: "CAVALRY", clan: "MSK", rating: 60 },
  { name: "Roman", category: "CAVALRY", clan: "DRAC", rating: 60 },
  { name: "Raindropz", category: "CAVALRY", clan: "IZpp Ingles", rating: 60 },
  { name: "Juvens", category: "CAVALRY", clan: "Asbanir", rating: 60 },
  { name: "Friedrich", category: "INFANTRY", clan: "Titod", rating: 60 },
  { name: "loskar", category: "CAVALRY", clan: "Titod", rating: 60 },
  { name: "Lazcano", category: "CAVALRY", clan: "MSK", rating: 60 },
  { name: "chonkRick", category: "INFANTRY", clan: "IZpp Ingles", rating: 60 },
  { name: "RAPTOR", category: "INFANTRY", clan: "SVCI", rating: 60 },
  { name: "Reik", category: "INFANTRY", clan: "DRAC", rating: 60 },
  { name: "Trainboy", category: "CAVALRY", clan: "IZpp Ingles", rating: 60 },
  { name: "LUGANO", category: "CAVALRY", clan: "MSK", rating: 60 },
  { name: "Pantrubka", category: "CAVALRY", clan: "SVCI", rating: 60 },
  { name: "Darius", category: "INFANTRY", clan: "DRAC", rating: 60 },
  { name: "Tiamouu", category: "CAVALRY", clan: "SVCI", rating: 60 },
  { name: "ArrowMaster", category: "CAVALRY", clan: "SVCI", rating: 60 },
  { name: "Lilith", category: "CAVALRY", clan: "IZpp Ingles", rating: 60 },
  { name: "Grengar", category: "INFANTRY", clan: "SVCI", rating: 60 },
  { name: "Samurai", category: "ARCHER", clan: "DRAC", rating: 60 },
  { name: "Greeny", category: "ARCHER", clan: "Asbanir", rating: 60 },
  { name: "Zuzuj", category: "INFANTRY", clan: "SVCI", rating: 60 },
  { name: "MrCRAZYGHOST", category: "ARCHER", clan: "Asbanir", rating: 60 },
  { name: "ElRomano05", category: "CAVALRY", clan: "DRAC", rating: 60 },
  { name: "Abushaka", category: "INFANTRY", clan: "Titod", rating: 60 },
  { name: "BadBrothers", category: "INFANTRY", clan: "Titod", rating: 60 },
  { name: "Wolves", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "alfred", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "Kryptoknight", category: "CAVALRY", clan: "Titod", rating: 60 },
  { name: "Magiccc", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "MrPostman", category: "INFANTRY", clan: "IZpp Ingles", rating: 60 },
  { name: "screw", category: "INFANTRY", clan: "SVCI", rating: 60 },
  { name: "Hawkpresto", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "Titan", category: "INFANTRY", clan: "SVCI", rating: 60 },
  { name: "Yuniku", category: "INFANTRY", clan: "IZpp Ingles", rating: 60 },
  { name: "nice toes xx", category: "INFANTRY", clan: "IZpp Ingles", rating: 60 },
  { name: "D-Bonkey", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "zombie", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "Waff", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "MintMango", category: "CAVALRY", clan: "DRAC", rating: 60 },
  { name: "Legend", category: "INFANTRY", clan: "Titod", rating: 60 },
  { name: "kaczman", category: "INFANTRY", clan: "IZpp Ingles", rating: 60 },
  { name: "sufel", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "Aemond", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "ScottyDave", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "gordek", category: "INFANTRY", clan: "Titod", rating: 60 },
  { name: "Tutel", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "Emilio Warhammer", category: "INFANTRY", clan: "Asbanir", rating: 60 },
  { name: "alyx", category: "INFANTRY", clan: "DRAC", rating: 60 },
  { name: "aegor", category: "INFANTRY", clan: "MSK", rating: 60 },
  { name: "SnowmarkPhoenix", category: "INFANTRY", clan: "DRAC", rating: 60 },
]

// Division G (Rating 55)
export const PLAYERS_G = [
  { name: "Impact", category: "CAVALRY", clan: "XIIth", rating: 55 },
  { name: "Ghostopo", category: "CAVALRY", clan: "ALMO", rating: 55 },
  { name: "Uberto", category: "CAVALRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Latash", category: "CAVALRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Papaj", category: "CAVALRY", clan: "Kopl 2", rating: 55 },
  { name: "Dajdad", category: "CAVALRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Hanzamut", category: "ARCHER", clan: "Bloody Degenerates", rating: 55 },
  { name: "Darthamau", category: "ARCHER", clan: "ALMO", rating: 55 },
  { name: "Maska", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "SucukuYumurta", category: "CAVALRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "TheHunter", category: "CAVALRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Pulpet", category: "CAVALRY", clan: "Kopl 2", rating: 55 },
  { name: "Heily", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "JonSnow", category: "ARCHER", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Agony", category: "CAVALRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Luxer", category: "CAVALRY", clan: "Kopl 2", rating: 55 },
  { name: "Mr Sneaky47", category: "CAVALRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Cael", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "Dyn", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Havoc", category: "INFANTRY", clan: "Kopl 2", rating: 55 },
  { name: "Hurri", category: "INFANTRY", clan: "Kopl 2", rating: 55 },
  { name: "Biggson", category: "CAVALRY", clan: "Kopl 2", rating: 55 },
  { name: "Merlyn", category: "CAVALRY", clan: "Inferno Squad", rating: 55 },
  { name: "Bugay", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "Seraph", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "Aimo Cat", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "SS Suther", category: "ARCHER", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Asinner", category: "CAVALRY", clan: "XIIth", rating: 55 },
  { name: "Masteranx", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Antares Mayer", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "ErviTrush", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "Manifest Kizi", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Sml", category: "INFANTRY", clan: "Kopl 2", rating: 55 },
  { name: "Gerunda", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "Bruockiller", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "DrBright", category: "INFANTRY", clan: "Kopl 2", rating: 55 },
  { name: "Pashanoob", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "Metrix", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Kerasunta", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Staza", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Rune", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Percival", category: "INFANTRY", clan: "XIIth", rating: 55 },
  { name: "PauCat", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "Kakarot", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "KaxumbaBoy", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "Hamzamcrn54", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Ury18", category: "CAVALRY", clan: "ALMO", rating: 55 },
  { name: "Melkim", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "ApolloN", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Nao", category: "INFANTRY", clan: "Bloody Degenerates", rating: 55 },
  { name: "Kn1pt", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Enass", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "LoveCompany", category: "INFANTRY", clan: "Kopl 2", rating: 55 },
  { name: "Ludovico", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Valkyron", category: "INFANTRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Kargator", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Raul Meireles", category: "CAVALRY", clan: "Skyborn Sentinels", rating: 55 },
  { name: "Ardhem", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Chadius", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Doebrekir", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Furkan", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Victores", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "TaloS", category: "INFANTRY", clan: "ALMO", rating: 55 },
  { name: "ISJBozkurt", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Sercius", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Rodrik", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
  { name: "Victors", category: "INFANTRY", clan: "Inferno Squad", rating: 55 },
]

// Division H (Rating 50)
export const PLAYERS_H = [
  { name: "Hispano", category: "CAVALRY", clan: "CI Alimerka", rating: 50 },
  { name: "ElGranChamo", category: "CAVALRY", clan: "CI Alimerka", rating: 50 },
  { name: "Azur", category: "CAVALRY", clan: "S2G", rating: 50 },
  { name: "Lurly", category: "CAVALRY", clan: "VEMO", rating: 50 },
  { name: "gorry", category: "CAVALRY", clan: "VEMO", rating: 50 },
  { name: "VejVar", category: "CAVALRY", clan: "SVCI B", rating: 50 },
  { name: "Aric", category: "CAVALRY", clan: "LA", rating: 50 },
  { name: "Crimson", category: "CAVALRY", clan: "HOST", rating: 50 },
  { name: "^Angel^", category: "CAVALRY", clan: "LA", rating: 50 },
  { name: "zcovi", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "R2Paul", category: "CAVALRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Kasten", category: "ARCHER", clan: "LA", rating: 50 },
  { name: "Yuki", category: "ARCHER", clan: "HOST", rating: 50 },
  { name: "Last Dance", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Micaito", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "Odin", category: "CAVALRY", clan: "LA", rating: 50 },
  { name: "Philippe", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "momot", category: "CAVALRY", clan: "CI Alimerka", rating: 50 },
  { name: "SenTy", category: "CAVALRY", clan: "SVCI B", rating: 50 },
  { name: "toxicossis", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "BiraXiebe", category: "CAVALRY", clan: "HOST", rating: 50 },
  { name: "Astar", category: "ARCHER", clan: "S2G", rating: 50 },
  { name: "Kasparhauzer", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Casca", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "Aoman", category: "INFANTRY", clan: "SVCI B", rating: 50 },
  { name: "Runnerblade", category: "CAVALRY", clan: "HOST", rating: 50 },
  { name: "Endzellu", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "lennell", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "Loop", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "Isak_1903", category: "CAVALRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "CapitaneoPaeroa", category: "CAVALRY", clan: "SVCI B", rating: 50 },
  { name: "Peppy", category: "ARCHER", clan: "SVCI B", rating: 50 },
  { name: "BhustBramburek", category: "INFANTRY", clan: "SVCI B", rating: 50 },
  { name: "Knalex", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "Wolf", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "TeaRin", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Adrian", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "Marnaus", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Minguito", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Plushka", category: "ARCHER", clan: "VEMO", rating: 50 },
  { name: "Petuardo", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Vedmak", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Mange", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Mark", category: "CAVALRY", clan: "S2G", rating: 50 },
  { name: "Sodex", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "Pex", category: "INFANTRY", clan: "SVCI B", rating: 50 },
  { name: "Master Giles", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "Gatto", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Annozker", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "Felix", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "Juan9a", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Ancodi", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Batuhan", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "no serenity", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Altaic", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "Arthas Menethil", category: "ARCHER", clan: "Nordic Vanguard", rating: 50 },
  { name: "lil YODA", category: "INFANTRY", clan: "HOST", rating: 50 },
  { name: "killerBrichy", category: "INFANTRY", clan: "SVCI B", rating: 50 },
  { name: "Janin", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "Otto", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "Chester Navy Blue", category: "INFANTRY", clan: "S2G", rating: 50 },
  { name: "Lancelot", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Ralle", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Werner", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Andy", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "hbr", category: "INFANTRY", clan: "VEMO", rating: 50 },
  { name: "Bobafit", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Akyla", category: "INFANTRY", clan: "LA", rating: 50 },
  { name: "NATURIOUS", category: "INFANTRY", clan: "Nordic Vanguard", rating: 50 },
  { name: "Chandalf", category: "INFANTRY", clan: "CI Alimerka", rating: 50 },
  { name: "Duncan", category: "INFANTRY", clan: "VEMO", rating: 50 },
]

// Division I (Rating 50)
export const PLAYERS_I = [
  { name: "Merthuz", category: "CAVALRY", clan: "BVRA", rating: 50 },
  { name: "Krabby Pattyson", category: "CAVALRY", clan: "BDCT", rating: 50 },
  { name: "Grium", category: "CAVALRY", clan: "BDCT", rating: 50 },
  { name: "DragonElite", category: "CAVALRY", clan: "FL", rating: 50 },
  { name: "Clovd", category: "CAVALRY", clan: "BDCT", rating: 50 },
  { name: "MERZECI", category: "CAVALRY", clan: "BVRA", rating: 50 },
  { name: "Vincent", category: "CAVALRY", clan: "DNI", rating: 50 },
  { name: "Spiritn", category: "CAVALRY", clan: "DNI", rating: 50 },
  { name: "Tavanemare", category: "CAVALRY", clan: "KOM", rating: 50 },
  { name: "Zireael", category: "CAVALRY", clan: "FL", rating: 50 },
  { name: "inying ungo", category: "CAVALRY", clan: "BVRA", rating: 50 },
  { name: "Meingott", category: "CAVALRY", clan: "BVRA", rating: 50 },
  { name: "blablabla", category: "CAVALRY", clan: "FL", rating: 50 },
  { name: "bob", category: "CAVALRY", clan: "DNI", rating: 50 },
  { name: "Shutikh Sutyagin", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "Sir Bedevere", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "diego", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Phantom Legend", category: "CAVALRY", clan: "DWDN", rating: 50 },
  { name: "Stefo80", category: "ARCHER", clan: "BDCT", rating: 50 },
  { name: "Sycor", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Muzlucay", category: "CAVALRY", clan: "BVRA", rating: 50 },
  { name: "Sakos", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Ibraam", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Kenzy", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Eser", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Kentence", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "Nerthuz", category: "ARCHER", clan: "BVRA", rating: 50 },
  { name: "Gama", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Bron", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Velmount", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "OKTV", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "nerty", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Gal", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "Veysel Han", category: "ARCHER", clan: "KOM", rating: 50 },
  { name: "basuranak", category: "INFANTRY", clan: "FL", rating: 50 },
  { name: "Dolunay", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "DJSA", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Bombproof", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Baldur", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "Feet Licker", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Mr Gergin", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Saltuk", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "KAIN", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "MULIERT", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Crown Emoji", category: "INFANTRY", clan: "FL", rating: 50 },
  { name: "Velimir", category: "INFANTRY", clan: "DWDN", rating: 50 },
  { name: "Beyaz", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Anil", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "KOM_Ghost", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Bingus", category: "INFANTRY", clan: "FL", rating: 50 },
  { name: "Alucard", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Kuesh", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Prismo", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Wertoguz", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "ErZak", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Xabi", category: "ARCHER", clan: "DWDN", rating: 50 },
  { name: "NRTH FERIKAL", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Okeanoss", category: "INFANTRY", clan: "FL", rating: 50 },
  { name: "Lothbrok62", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Saygin", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Esmond", category: "INFANTRY", clan: "DNI", rating: 50 },
  { name: "Kont Laesha", category: "INFANTRY", clan: "KOM", rating: 50 },
  // "Sir Bedevere" is duplicated in the user list, I'll keep both if they are distinct in the DB or upsert will handle it.
  // Actually upsert by name means the second one will update the first one. That is fine.
  { name: "plasuedo", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Gtef", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Laesh", category: "INFANTRY", clan: "KOM", rating: 50 },
  { name: "Veterinarian", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "CHIMP", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "Kartal gaming", category: "INFANTRY", clan: "BVRA", rating: 50 },
  { name: "Damascus", category: "INFANTRY", clan: "BDCT", rating: 50 },
  { name: "NecdetKomutan", category: "INFANTRY", clan: "KOM", rating: 50 },
]

// Division J (Rating 50)
export const PLAYERS_J = [
  { name: "LindaGeto", category: "CAVALRY", clan: "UkrainePower", rating: 50 },
  { name: "Kaysk", category: "CAVALRY", clan: "XIIth B", rating: 50 },
  { name: "Kvaka", category: "CAVALRY", clan: "UkrainePower", rating: 50 },
  { name: "persev", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "Benjen Stark", category: "CAVALRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Tong", category: "CAVALRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Fynn", category: "CAVALRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "Cool", category: "ARCHER", clan: "UkrainePower", rating: 50 },
  { name: "Tiquezius", category: "CAVALRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "d4nte", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "Jules", category: "CAVALRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Turbobeecke", category: "ARCHER", clan: "Teutonic Shadows", rating: 50 },
  { name: "Alexander", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "fweber", category: "ARCHER", clan: "Teutonic Sanctum", rating: 50 },
  { name: "oliver_nordal", category: "CAVALRY", clan: "IZpp Employed", rating: 50 },
  { name: "Funnyboy38", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Wizard", category: "ARCHER", clan: "XIIth B", rating: 50 },
  { name: "TtOd_Azrael", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Anjin", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Sia", category: "CAVALRY", clan: "XIIth B", rating: 50 },
  { name: "Peter", category: "CAVALRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Daiser", category: "ARCHER", clan: "Teutonic Shadows", rating: 50 },
  { name: "Roobi4", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "titel", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "Tarkatan04", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "Deathminer", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Derorden", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Nemi", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Pargali", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Bluebell", category: "INFANTRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "raslQT", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "Walther", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "glorion", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
  { name: "KaiserVespasian", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Pitu", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "Hector", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "JUUL", category: "ARCHER", clan: "IZpp Employed", rating: 50 },
  { name: "Hugo2dog", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Kenvay_Aim", category: "ARCHER", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Surelynot", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "NAKLYCE SEFER", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Pony", category: "INFANTRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "Alexander The Great", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "ToxicisGood", category: "INFANTRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "Rita", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Tehalon", category: "CAVALRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "DrMuffin", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "Shushe", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "DerWolf300", category: "CAVALRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "Elshadow", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Pasetko_Se_Vrodylo", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "SkyofMy", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "jaezkerfitten", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Lisey", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Bozkurt", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
  { name: "Claud", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "onreyduargon1", category: "INFANTRY", clan: "Teutonic Shadows", rating: 50 },
  { name: "Orpheus", category: "INFANTRY", clan: "Kardesler Pide Oküzleri", rating: 50 },
  { name: "Shady Pricefield", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Rakk", category: "INFANTRY", clan: "CI Iberian Lions", rating: 50 },
  { name: "Aragorn", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "FcknUbbe", category: "INFANTRY", clan: "Teutonic Sanctum", rating: 50 },
  { name: "femo de Benj", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "davidgabri_28", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
  { name: "Aspid", category: "INFANTRY", clan: "UkrainePower", rating: 50 },
  { name: "Noob", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
  { name: "Haines", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
  { name: "Kipnoxa", category: "INFANTRY", clan: "XIIth B", rating: 50 },
  { name: "OCB slim", category: "ARCHER", clan: "IZpp Employed", rating: 50 },
  { name: "Galaxyhunter_18", category: "INFANTRY", clan: "IZpp Employed", rating: 50 },
]

export const ALL_PLAYERS = [
  ...PLAYERS_A,
  ...PLAYERS_B,
  ...PLAYERS_C,
  ...PLAYERS_D,
  ...PLAYERS_E,
  ...PLAYERS_F,
  ...PLAYERS_G,
  ...PLAYERS_H,
  ...PLAYERS_I,
  ...PLAYERS_J,
]

